In [1]:
import pandas as pd

In [8]:
iris_filename = '/content/Iris.csv'
iris = pd.read_csv(iris_filename, sep=',',
                  decimal='.',header=None,
                  names = ['sepal_length','sepal_width',
                          'petal_length','petal_width',
                          'target'])

In [9]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, Id to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  151 non-null    object
 1   sepal_width   151 non-null    object
 2   petal_length  151 non-null    object
 3   petal_width   151 non-null    object
 4   target        151 non-null    object
dtypes: object(5)
memory usage: 7.1+ KB

In [10]:
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
target          0
dtype: int64

In [11]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'], dtype='object')

In [12]:
iris['target']

Id            Species
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: target, Length: 151, dtype: object

In [13]:
iris.set_index('target', inplace=True)
print(iris.head())

              sepal_length   sepal_width   petal_length   petal_width
target
Species      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Iris-setosa           5.10          3.50           1.40          0.20
Iris-setosa           4.90          3.00           1.40          0.20
Iris-setosa           4.70          3.20           1.30          0.20
Iris-setosa           4.60          3.10           1.50          0.20

In [14]:
iris.reset_index(drop=True, inplace=True)

In [15]:
iris

      sepal_length   sepal_width   petal_length   petal_width
0    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
1             5.10          3.50           1.40          0.20
2             4.90          3.00           1.40          0.20
3             4.70          3.20           1.30          0.20
4             4.60          3.10           1.50          0.20
..             ...           ...            ...           ...
146           6.70          3.00           5.20          2.30
147           6.30          2.50           5.00          1.90
148           6.50          3.00           5.20          2.00
149           6.20          3.40           5.40          2.30
150           5.90          3.00           5.10          1.80

[151 rows x 4 columns]

In [16]:
iris.head(10)

    sepal_length   sepal_width   petal_length   petal_width
0  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
1           5.10          3.50           1.40          0.20
2           4.90          3.00           1.40          0.20
3           4.70          3.20           1.30          0.20
4           4.60          3.10           1.50          0.20
5           5.00          3.60           1.40          0.20
6           5.40          3.90           1.70          0.40
7           4.60          3.40           1.40          0.30
8           5.00          3.40           1.50          0.20
9           4.40          2.90           1.40          0.20

In [18]:
iris2 = pd.read_csv(iris_filename)
iris2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
iris2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [20]:
iris2['sepal_ratio'] = iris2['SepalLengthCm'] / iris2['SepalWidthCm']
print(iris2.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

   sepal_ratio
0     1.457143
1     1.633333
2     1.468750
3     1.483871
4     1.388889

In [21]:
irisn['petal_area'] = irisn.apply(lambda row: row['PetalLengthCm'] * row['PetalWidthCm'], axis=1)
print(irisn.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

   petal_area
0        0.28
1        0.28
2        0.26
3        0.30
4        0.28